### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by ringods** [Adphorus/zenhub-charts#6]
I have a local test setup running, connected to a single Git repository. After fetching the initial data, I browse to the zenhub charts app, but I get an empty spot for the chart. Looking at the logs, I have this stacktrace:

```
web_1       | Internal Server Error: /cycle-time/chart-data/
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
web_1       |     response = get_response(request)
web_1       |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1       |     response = self.process_exception_by_middleware(e, request)
web_1       |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1       |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
web_1       |     return self.dispatch(request, *args, **kwargs)
web_1       |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
web_1       |     return handler(request, *args, **kwargs)
web_1       |   File "/opt/zenhub-charts/charts/views.py", line 205, in get
web_1       |     repo_name, since, until, durations))
web_1       |   File "/opt/zenhub-charts/charts/views.py", line 35, in get_chart_data
web_1       |     since = self._py_datetime(int(float(since)))
web_1       | ValueError: cannot convert float NaN to integer
```

PS: please ignore the `web_1` prefix. This comes from my local Docker Compose setup.

Any idea where to start looking for the root cause?

**Comment by ringods** [comment]
A bit further investigation leads me to the following thinking path.

I see log entries like this when clicking on the timeframe scale buttons in the upper left:
`[08/Dec/2017 12:32:45] "GET /cycle-time/chart-data/?repo&since=NaN&until=NaN&durations HTTP/1.1" 500 13469`

So the `NaN` comes from the `From` and `To` fields not being filled in. But that one might be related to these log entries:

`/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField Issue.latest_transfer_date received a naive datetime (2016-12-08 12:28:33.982674) while time zone support is active.`

Does this mean that the `fetch` process did not store the DateTime objects correctly in the DB?

I'm using PostgreSQL and looking at the `boards_issue` table, the type of the `latest_transfer_date` is `TIMESTAMP WITH TIME ZONE`.

**Comment by ringods** [comment]
Checking the database, I have 5 entries where the `latest_transfer_date` is `NULL`. 4 of them are actually pull requests which I'm not interested in. The last one is an issue I created about an hour before the initial fetch. So there weren't any transitions yet.

Questions:
* shouldn't PR's be excluded?
* Can certain code paths fail because the `last_transferred_date` is still `NULL`?

**Comment by ringods** [comment]
@tatterdemalion or @mkg0 could one of you have a look at the questions I have in my previous comment?

**Comment by ringods** [comment]
I'm changing the code to not allow `null` values in `Issue.latest_transfer_date`.

#7

**Comment by tatterdemalion** [comment]
I am trying to replicate the problem. I dropped my database recently, so it may take some time. We probably need to change the `fetch` script to ignore the issues without `latest_transfer_date` as well.

**Comment by ringods** [comment]
@tatterdemalion when I browse to the root URL (http://127.0.0.1:8080/), which piece of code is responsible for filling in the start/end date in the upper right of the main screen?

**Comment by tatterdemalion** [comment]
Highcharts does it internally. When you change the duration it makes another request to `/cycle-time/chart-data/`. Take a look at this one: https://github.com/Adphorus/zenhub-charts/blob/master/charts/views.py#L28

**Comment by ringods** [comment]
Yes, that is when I *change* the duration. 

But am I right to assume that because the From/To fields are not filled in the root/initial view, changing a duration sends `NaN` to the `ChartsResponseView` for `since` and/or `until`?

**Comment by tatterdemalion** [comment]
Root URL does not work at all. I think that is the problem. If you go to `http://localhost:8000?repo=<your_repo_name>` it will probably work.

I will redirect root url to the first repository by default.

**Comment by ringods** [comment]
Indeed. Thanks for the help. Redirecting would indeed be a good thing to prevent others of also loosing time on this. 😄

**Comment by tatterdemalion** [comment]
I should have done this before. Thanks for pointing it out. 

https://github.com/Adphorus/zenhub-charts/pull/8

I merged it. It should work now.
